steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(node_version)"
    displayName: "Install Node.js"

  # workaround for https://github.com/yarnpkg/yarn/issues/6900
  - script: npm install -g yarn@1.12.3
    displayName: "Install Node v4 compatible Yarn"
    condition: eq(variables.node_version, 4)

  # workaround for https://github.com/yarnpkg/yarn/issues/6900
  - script: npm install -g yarn@1.12.3
    displayName: "Install Node v5 compatible Yarn"
    condition: eq(variables.node_version, 5)

  # workaround for https://github.com/yarnpkg/yarn/issues/6900
  - script: npm install -g yarn@1.12.3
    displayName: "Install Node v6 compatible Yarn"
    condition: eq(variables.node_version, 6)

  # workaround for https://github.com/yarnpkg/yarn/issues/6900
  - script: npm install -g yarn@1.12.3
    displayName: "Install Node v7 compatible Yarn"
    condition: eq(variables.node_version, 7)
