[build]
  command = "yarn build:website"
  publish = "website/build/"

[build.environment]
  NODE_VERSION = "lts/*"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/unpkg.com"
  to = "https://unpkg.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[headers]]
  for = "/worker.mjs"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' unpkg.com; script-src 'self' unpkg.com 'unsafe-eval'; worker-src 'self' unpkg.com"
