name: Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Build Results
      # Prevent error on re-run
      # https://github.com/actions/cache/issues/107#issuecomment-556037278
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      id: build-cache
      uses: actions/cache@v1
      with:
        path: .cache
        key: v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ hashFiles('scripts/build/**/*') }}-${{ github.ref }}-
        restore-keys: |
          v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ hashFiles('scripts/build/**/*') }}-${{ github.ref }}-
          v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ hashFiles('scripts/build/**/*') }}-refs/heads/${{ github.base_ref }}-
          v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ hashFiles('scripts/build/**/*') }}-refs/heads/master-

    - uses: preactjs/compressed-size-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: andresz1/size-limit-action@v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
